/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hetatech.mkb;

import org.hetatech.mkb.ui.JavaFxApplicationMainFrom;

public class App {

    public static void main(String... args) {
        JavaFxApplicationMainFrom javaFxApplicationMainFrom = new JavaFxApplicationMainFrom();
        javaFxApplicationMainFrom.startApplication(args);
    }
}
