/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hetatech.mkb;

import org.hetatech.mkb.db.Db;
import org.hetatech.mkb.ui.JavaFxApplicationMainFrom;

public class App {

    public static void main(String... args) {

        Db.getInstance().testDbDriver();

        JavaFxApplicationMainFrom javaFxApplicationMainFrom = new JavaFxApplicationMainFrom();
        javaFxApplicationMainFrom.startApplication(args);
    }
}
